apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    app: {{ include "nginx.name" . }}
  annotations:
    argocd-image-updater.argoproj.io/image-list: "nginx={{ .Values.image.repository }}"
    argocd-image-updater.argoproj.io/nginx.update-strategy: "latest"
    argocd-image-updater.argoproj.io/nginx.values: "image.tag"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nginx.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx.name" . }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
