nginx:
  replicaCount: 1

  image:
    repository: harbor-dw.cowave.kr/argocd-dev/nginx
    tag: "1.28.0"
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: argo-secret

  containerPort: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
