nginx:
  replicaCount: 1

  image:
    repository: harbor-dw.cowave.kr/argocd/nginx
    tag: "1.28.0"
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: argocd-harbor-secret

  containerPort: 80

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations: {}
    path: /
    hosts:
      - chart-example.local
    tls: []

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}
